services:
  - type: web
    name: anonymous-chat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
